routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Category\CategoryFacade;
use Bittacora\Bpanel4\Products\Http\Controllers\ProductAdminController;
use Bittacora\Bpanel4\Products\Http\Controllers\ProductPublicController;
use Bittacora\Bpanel4\Products\Models\Product;

Route::prefix('/productos')->name('bpanel4-products-public.')->middleware(['web'])->group(function () {
    Route::get('/', [ProductPublicController::class, 'index'])->name('index');
});

Route::prefix(config('bpanel4-products.product_route_prefix'))->name('bpanel4-products-public.')->middleware(['web'])->group(function () {
    Route::get(config('bpanel4-products.product_url_structure'), [ProductPublicController::class, 'show'])->name('show');
});


Route::prefix('bpanel/productos')->name('bpanel4-products.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(function () {
        Route::get('/', [ProductAdminController::class, 'index'])->name('index');
        Route::get('/nuevo', [ProductAdminController::class, 'create'])->name('create');
        Route::get('{model}/editar/{locale?}', [ProductAdminController::class, 'edit'])->name('edit');
        Route::post('/store', [ProductAdminController::class, 'store'])->name('store');
        Route::post('{product}/actualizar', [ProductAdminController::class, 'update'])->name('update');
        Route::delete('{product}/destroy', [ProductAdminController::class, 'destroy'])->name('destroy');

        CategoryFacade::addRoutes('product', Product::class, ProductAdminController::class);
    });

Route::prefix('bpanel/etiquetas/productos')->name('bpanel4-products.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(function () {
        Route::get('/condiciones-piel')->name('skin-conditions');
        Route::get('/protocolos')->name('protocols');
    });

resources/views/bpanel/_form.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-products::form.new-product'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ $panelTitle }}</span>
            </h4>
            @if(isset($language))
                @include('language::partials.form-languages', ['model' => $product, 'edit_route_name' => 'bpanel4-products.edit',  'currentLanguage' => $language])
            @endif
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{ $action }}" enctype="multipart/form-data">
            @csrf
            @livewire('form::input-text', ['name' => 'name', 'labelText' => __('bpanel4-products::product.name'), 'required'=>true, 'value' => old('name') ?? $product?->getName() ])
            @livewire('form::input-text', ['name' => 'reference', 'labelText' => __('bpanel4-products::product.reference'), 'required'=>true, 'value' => old('reference') ?? $product?->getReference() ])
            @livewire('form::textarea', ['name' => 'short_description', 'labelText' => __('bpanel4-products::product.short_description'), 'value' => old('short_description') ?? $product?->getShortDescription() ])
            @livewire('utils::tinymce-editor', ['name' => 'description', 'labelText' => __('bpanel4-products::product.description'), 'value' => old('description') ?? $product?->getDescription() ])
            @stack('after-description-additional-fields')
            <x-bpanel4-vat::select :model="$product"/>
            @livewire('form::input-number', ['name' => 'price', 'labelText' => __('bpanel4-products::product.price_form_label'), 'required'=>true, 'value' => old('price') ?? $product?->getPrice()->toFloat(), 'min' => 0, 'step' => 0.0001, 'fieldWidth' => 7, 'labelWidth' => 3 ])
            <x-price-preview vatFieldId="vat_rate_id" priceFieldId="price"></x-price-preview>
            @livewire('form::input-number', ['name' => 'discounted_price', 'labelText' => __('bpanel4-products::product.discounted_price_form_label'), 'required'=>false, 'value' => old('discounted_price') ?? $product?->getDiscountedPrice()?->toFloat(), 'min' => 0, 'step' => 0.0001, 'fieldWidth' => 7, 'labelWidth' => 3, 'helpText' => __('bpanel4-products::form.discounted_price_help') ])
            <x-price-preview vatFieldId="vat_rate_id" priceFieldId="discounted_price"></x-price-preview>
            @livewire('form::input-number', ['name' => 'size', 'labelText' => __('bpanel4-products::product.size'), 'required'=>false, 'value' => old('size') ?? $product?->getSize(), 'step' => 0.01, 'min' => 0, 'fieldWidth' => 7, 'labelWidth' => 3, 'helpText' => __('bpanel4-products::form.size_help'), 'placeholder' => 'Por ejemplo, tamaño del envase: 100, 200, 500 (sin indicar la unidad de medida)' ])
            @livewire('form::input-text', ['name' => 'unit', 'labelText' => __('bpanel4-products::form.unit'), 'required'=>false, 'value' => old('unit') ?? $product?->getUnit(),
            'placeholder' => __('bpanel4-products::form.unit-placeholder') ])
            @livewire('form::input-number', ['name' => 'stock', 'labelText' => __('bpanel4-products::product.stock'), 'required'=>true, 'value' => old('stock') ?? $product?->getStock(), 'step' => 1, 'min' => 0, 'fieldWidth' => 7, 'labelWidth' => 3 ])
            <x-bpanel4-category::select :model="$product" :categories="$categories" :multiple="true"/>
            @if (null !== $product and null !== $product->content)
                <div class="row">
                    <div class="col-3">&nbsp;</div>
                    <div class="col-7">
                        @livewire('content-multimedia::upload-content-multimedia-widget', [
                        'fieldName' => 'product_images',
                        'model' => $product,
                        'allowedFormats' => 'image/jpeg, image/png, image/webp',
                        'allowedExtensions' => 'jpg,jpeg,png,webp'
                        ])
                        @livewire('content-multimedia-images::content-multimedia-images-widget', [
                        'contentId' => $product->content->id,
                        'module' => 'product',
                        'permission' => 'product.edit'
                        ])
                    </div>
                </div>
            @else
                <div class="row">
                    <div class="col-3"></div>
                    <div class="col-7">
                        <x-bpanel4-warning message="Para añadir imágenes al producto, primero debe guardarlo."/>
                    </div>
                </div>
            @endif
            <div class="form-group form-row">
                <div class="col-sm-3 col-form-label text-sm-right pr-0"></div>
                <div class="col-sm-7">
                    @livewire('seo::seo-fields', ['model' => $product])
                </div>
            </div>
            @livewire('form::input-number', ['name' => 'position', 'labelText' => __('bpanel4-products::form.position'), 'required'=>true, 'value' => old('position') ?? $product?->getPosition() ?? 0, 'step' => 1, 'min' => -999999, 'max' => '999999', 'fieldWidth' => 7, 'labelWidth' => 3, 'helpText' => __('bpanel4-products::form.position_field_help') ])
            @stack('before-active-additional-fields')
            @livewire('form::input-checkbox', ['name' => 'active', 'value' => 1, 'checked' => old('active') ?? $product?->isActive(), 'labelText' => __('bpanel4-products::product.active'), 'bpanelForm' => true])
            @livewire('form::input-checkbox', ['name' => 'featured', 'value' => 1, 'checked' => old('featured') ?? $product?->isFeatured(), 'labelText' => __('bpanel4-products::product.featured'), 'bpanelForm' => true])
            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'update'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
            @if($product?->getId() !== null)
                <input type="hidden" name="id" value="{{ $product->getId() }}">
            @endif

            @if(isset($language))
                <input type="hidden" name="locale" value="{{ $language }}">
            @endif
        </form>
    </div>

@endsection

resources/views/bpanel/create.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-products::form.new-product'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-products::form.new-product') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-products.store')}}">
            @include('bpanel4-products::bpanel._form', ['panelTitle' => __('bpanel4-products::form.new-product')])
        </form>
    </div>

@endsection

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', __('bpanel4-products::form.edit-product'))

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-products::form.edit-product') }}</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('bpanel4-products.store')}}">
            @include('bpanel4-products::bpanel._form', ['panelTitle' => __('bpanel4-products::form.edit-product')])
        </form>
    </div>

@endsection

resources/views/bpanel/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Productos')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-products::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('bpanel4-products::livewire.products-table', [], key('bpanel4-products-datatable'))
        </div>
    </div>

    @if ($lowStockProducts->count() > 0)
        <div class="alert alert-danger mt-5">
            <strong class="mb-3 d-block"><i class="fas fa-box"></i> Los siguientes productos tienen stock bajo:</strong>
        @foreach($lowStockProducts as $lowStockProduct)
            <div class="pb-2">
                <a href="{{ route('bpanel4-products.edit', ['model' => $lowStockProduct]) }}" target="_blank">{!! strip_tags($lowStockProduct->name) !!}</a> (Stock: {{ $lowStockProduct->stock }})
            </div>
        @endforeach
        </div>
    @endif

@endsection

resources/views/bpanel/livewire/datatable-columns/actions.blade.php
@livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-products', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el producto?'], key('user-buttons-'.$row->id))

resources/views/bpanel/livewire/datatable-columns/active.blade.php
@livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))

resources/views/bpanel/livewire/datatable-columns/featured.blade.php
@livewire('utils::datatable-default', ['fieldName' => 'featured', 'model' => $row, 'value' => $row->featured, 'size' => 'xxs'], key('featured-user-'.$row->id))

resources/views/bpanel/livewire/product-datatable.blade.php
<td class="align-middle">
    <div class="text-center">
        {{$row->name}}
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        {{$row->reference}}
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        {{$row->size}} {{$row->unit}}
    </div>
</td>
<td class="align-middle">
    <div class="text-center">
        {{ $row->getPrice() }}
    </div>
</td>
<td class="align-middle">
    @if(!empty($row->getDiscountedPrice()))
        <div class="text-center">
            {{ $row->getDiscountedPrice() }}
        </div>
    @endif
</td>
<td class="align-middle">
    <div class="text-center">
        {{\Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $row->created_at)->format('d/m/Y')}}
    </div>
</td>
<td class="align-middle">
    @livewire('utils::datatable-default', ['fieldName' => 'active', 'model' => $row, 'value' => $row->active, 'size' => 'xxs'], key('active-user-'.$row->id))
</td>
<td class="align-middle">
    @livewire('utils::datatable-default', ['fieldName' => 'featured', 'model' => $row, 'value' => $row->featured, 'size' => 'xxs'], key('featured-user-'.$row->id))
</td>
<td class="align-middle">
    <div class="text-center">
        @livewire('utils::datatable-action-buttons', ['actions' => ["edit", "delete"], 'scope' => 'bpanel4-products', 'model' => $row, 'permission' => ['edit', 'delete'], 'id' => $row->id, 'message' => 'el producto?'], key('user-buttons-'.$row->id))
    </div>
</td>

resources/views/shortcodes/featured-products.blade.php
<div class="featured-products">
    @foreach($products as $product)
        <div class="product">
            @if (!empty($product->getFeaturedImages()))
                <div class="img-container">
                    <img src="{{ $product->getFeaturedImages()[0]->getFullUrl() }}"
                         alt="{{ $product->getName() }}">
                </div>
            @else
                <div class="img-container">
                    <img src="/assets/img/product-placeholder.png" alt="">
                </div>
            @endif
            <div class="name">{{ $product->getName() }}</div>
            <div class="price">{{ $product->getPrice() }}</div>
        </div>
    @endforeach
</div>